### ISSUE TITLE
Direct support for Rust Hero file format

### ISSUE THREAD

**Issue by 1sra3l** [1sra3l/charcter-maker#1]
@igorfs10 Since I already had this program, I converted it to use `rpgstat = "3.0"`
This can be the playground for what you want a character file to really include, and a UI to configure it.
If we can make a good plan for organizing the data this would be a good place to try things out.
FLUID is great for visualizing data and then making it a program. 

I am using "Advanced" for the stats, but intend to support all 3 types in the program, specifically `Normal`  which is what I think we intend to use for Rust Hero.

I am currently working with TOML tables to build the "effectiveness" chart.  So keep in mind for images we could do something different like:
```toml
images =  { right = "/path/to/image", left = "/path/to/image", up = "/path/to/image", down = "/path/to/image"}
```
Or to support animations:
```toml
[animations]
left =  { one = "/path/to/image", two = "/path/to/image", three = "/path/to/image", four = "/path/to/image"}
right = { one = "/path/to/image", two = "/path/to/image", three = "/path/to/image", four = "/path/to/image"}
up = { one = "/path/to/image", two = "/path/to/image", three = "/path/to/image", four = "/path/to/image"}
down =  { one = "/path/to/image", two = "/path/to/image", three = "/path/to/image", four = "/path/to/image"}
```
